# Generated by Django 3.2.13 on 2022-05-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_possessingbook_withbook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WithBook',
            new_name='WishBook',
        ),
    ]
