# Generated by Django 3.2.13 on 2022-05-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_rename_withbook_wishbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='PossessingBook',
        ),
        migrations.DeleteModel(
            name='WishBook',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
