# Generated by Django 3.2.13 on 2022-05-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_possessingbook_wishbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishbook',
            name='insertdate',
            field=models.DateTimeField(verbose_name='insertdate'),
        ),
        migrations.AlterField(
            model_name='wishbook',
            name='updatedate',
            field=models.DateTimeField(verbose_name='updatedate'),
        ),
    ]
